#!/bin/bash
echo "=== NORDIC GLOBE PERFORMANCE CHECK ==="
echo ""
echo "File sizes:"
echo "  index.html: $(wc -c < index.html | numfmt --to=iec 2>/dev/null || wc -c < index.html) bytes"
echo "  Total photos: $(du -sh photos/ 2>/dev/null)"
echo "  Video: $(ls -lh bg/water-43.mp4 2>/dev/null | awk '{print $5}')"
echo ""
echo "Page count:"
echo "  HTML files: $(find . -name '*.html' | wc -l)"
echo "  City pages: $(find . -name 'cleaning-*.html' -o -name 'siivous-*.html' | wc -l)"
echo "  Blog posts: $(find blog/ -name '*.html' 2>/dev/null | wc -l)"
echo ""
echo "SEO checks:"
echo "  Schema.org blocks: $(grep -c 'application/ld+json' index.html)"
echo "  Meta tags: $(grep -c '<meta' index.html)"
echo "  Sitemap URLs: $(grep -c '<url>' sitemap.xml)"
echo ""
echo "Security headers in vercel.json:"
grep -c '"key"' vercel.json
